export const alertPopup = {
    noPopup: 'noPopup',
    wrongLandAlert: 'wrongLandAlert',
    plantingConfirmAlert: 'plantingConfirmAlert',
    detailTreePopup: 'detailTreePopup',
    cultivationTreePopup: 'cultivationTreePopup',
    usingItemConfirmAlert: 'usingItemConfirmAlert',
    usingItemNoneQuantityConfirmAlert: 'usingItemNoneQuantityConfirmAlert',
    loadingPopup: 'loadingPopup',
    platingTreeSuccessPopup: 'platingTreeSuccessPopup',
    platingTreeUnSuccessPopup: 'platingTreeUnSuccessPopup',
    usingItemForTreeSuccessPopup: 'usingItemForTreeSuccessPopup',
    usingItemForTreeUnSuccessPopup: 'usingItemForTreeUnSuccessPopup',
    limitNutritionAlert:'limitNutritionAlert',
    checkForSaleStatusAlert: 'checkForSaleStatusAlert',
    checkTreeAlreadyExistAlert: 'checkTreeAlreadyExistAlert',
    rechargeAlertPopup : 'rechargeAlertPopup',
    checkForSaleStatusForTreeAlert: 'checkForSaleStatusForTreeAlert',
    checkAlreadyHaveTreeAlert: 'checkAlreadyHaveTreeAlert',
    checkPlantTreeBeforeNutrient: 'checkPlantTreeBeforeNutrient',
    checkPlantTreeBeforeShovel: 'checkPlantTreeBeforeShovel',
    checkPlantTreeBeforeDroplet: 'checkPlantTreeBeforeDroplet',

};