const data = [
    {
        "itemId" : "C1",
        "name_ko" : "꼬마 악어",
        "name_en" : "Little Crocodile",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "언제나 웃고 있다. 엄마가 선물해준 옷|언제나 웃고 있다. 엄마가 선물해준 옷.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "언제나 웃고 있다. 엄마가 선물해준 옷|언제나 웃고 있다. 엄마가 선물해준 옷.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "언제나 웃고 있다. 엄마가 선물해준 옷.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 1000,
        "imagePath" : "little-crocodile.png",
        "type" : "character",
    },
    {
        "itemId" : "C2",
        "name_ko" : "꼬마 강아지",
        "name_en" : "Little Puppy",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "언제나 즐거운 아이. 동생을 피해 다닌다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "언제나 즐거운 아이. 동생을 피해 다닌다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "언제나 즐거운 아이. 동생을 피해 다닌다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 1000,
        "imagePath" : "little-puppy.png",
        "type" : "character",
    },
    {
        "itemId" : "C3",
        "name_ko" : "분홍 알파카",
        "name_en" : "Pink Alpaca",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 1000,
        "imagePath" : "pink-alpaca.png",
        "type" : "character",
    },
    {
        "itemId" : "C4",
        "name_ko" : "분홍 알파카",
        "name_en" : "Pumpkin Witch",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "언제나 당신을 바라만 보고 있는 동물.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 1000,
        "imagePath" : "pumpkin-witch-shop.png",
        "type" : "character",
    },
    {
        "itemId" : "T1",
        "name_ko" : "일반 나무",
        "name_en" : "Normal Tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "가장 일반적인 나무<br/>연 0.6%의 고정이율을 <br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 0.6%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "가장 일반적인 나무 연 0.6%의 고정이율을 <br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 0,
        "imagePath" : "normal-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T2",
        "name_ko" : "화이트 나무",
        "name_en" : "White Tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "눈이 덮여 있는 나무<br/>연 7.2%의 고정이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 7.2%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "눈이 덮여 있는 나무 연 7.2%의 고정이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 180,
        "imagePath" : "white-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T3",
        "name_ko" : "그린 나무",
        "name_en" : "Green tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "녹색으로 만들어진 나무<br/>연 7.8%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 7.8%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "녹색으로 만들어진 나무 연 7.8%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 260,
        "imagePath" : "green-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T4",
        "name_ko" : "블루 나무",
        "name_en" : "Blue tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "파란색으로 만들어진 나무<br/>연 8.4%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를  받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 8.4%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "파란색으로 만들어진 나무 연 8.4%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를  받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 350,
        "imagePath" : "blue-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T5",
        "name_ko" : "브론즈 나무",
        "name_en" : "Bronze tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "건강한 녹색의 나무<br/>연 9.6%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 9.6%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "건강한 녹색의 나무 연 9.6%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 480,
        "imagePath" : "bronze-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T6",
        "name_ko" : "실버 나무",
        "name_en" : "Silver tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "은색으로 덮여있는 나무<br/>연 11.4%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 11.4%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "은색으로 덮여있는 나무 연 11.4%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 760,
        "imagePath" : "silver-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T7",
        "name_ko" : "골드 나무",
        "name_en" : "Gold tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "금색으로 덮여있는 나무<br/>연 13.2%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 13.2%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "금색으로 덮여있는 나무 연 13.2%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 1500,
        "imagePath" : "gold-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T8",
        "name_ko" : "플래티넘 나무",
        "name_en" : "Platinum tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "금색으로 덮여있는 나무<br/>연 13.2%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 15%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "가장 좋은 나무 연 15%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 3000,
        "imagePath" : "platinum-tree.png",
        "type" : "blood-tree",
    },
    {
        "itemId" : "T9",
        "name_ko" : "다이아 몬드 나무",
        "name_en" : "Diamond tree",
        "name_vi" : "__",
        "descriptionForDetail_ko" : "전설 랜덤 박스에서만 받을<br/>수 있는 희귀한 나무<br/>연 45%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForDetail_en" : "",
        "descriptionForDetail_vi" : "",
        "descriptionForInventory_ko" : "연 이율이 45%를 가지고 있으며<br/>마우스 드래그로  나의 랜드위에 <br/>사용할 수 있다.",
        "descriptionForInventory_en" : "",
        "descriptionForInventory_vi" : "",
        "descriptionForShop_ko" : "전설 랜덤 박스에서만 받을 수 있는 희귀한 나무<br/>연 45%의 고정 이율을<br/>가지고 있다.<br/>하루마다 이자를 받는다.",
        "descriptionForShop_en" : "",
        "descriptionForShop_vi" : "",
        "interestRate" : 0,
        "price" : 0,
        "imagePath" : "diamond-tree.png",
        "type" : "blood-tree",
    },
];
