export const GET_CHARACTER_INVENTORY_BY_USER_SUCCESS = 'GET_CHARACTER_INVENTORY_BY_USER_SUCCESS';
export const GET_CHARACTER_INVENTORY_BY_USER_FAILURE = 'GET_CHARACTER_INVENTORY_BY_USER_FAILURE';

export const GET_ITEM_INVENTORY_BY_USER_SUCCESS = 'GET_ITEM_INVENTORY_BY_USER_SUCCESS';
export const GET_ITEM_INVENTORY_BY_USER_FAILURE = 'GET_ITEM_INVENTORY_BY_USER_FAILURE';

export const GET_GIFT_INVENTORY_BY_USER_SUCCESS = 'GET_GIFT_INVENTORY_BY_USER_SUCCESS';
export const GET_GIFT_INVENTORY_BY_USER_FAILURE = 'GET_GIFT_INVENTORY_BY_USER_FAILURE';

export const USE_ITEM_SUCCESS = 'USE_ITEM_SUCCESS';
export const USE_ITEM_FAILURE = 'USE_ITEM_FAILURE';

export const OPEN_RANDOM_BOX_SUCCESS = 'OPEN_RANDOM_BOX_SUCCESS';
export const OPEN_RANDOM_BOX_FAILURE = 'OPEN_RANDOM_BOX_FAILURE';

export const CLEAR_SUCCESS_ERROR = 'CLEAR_SUCCESS_ERROR';


export const CLEAR_PLANTED_TREES_RESULT = 'CLEAR_PLANTED_TREES_RESULT';

export const MOVE_TREE_INVENTORY_TO_MAP_SUCCESS = 'MOVE_TREE_INVENTORY_TO_MAP_SUCCESS';
export const MOVE_TREE_INVENTORY_TO_MAP_FAILURE = 'MOVE_TREE_INVENTORY_TO_MAP_FAILURE';

export const GET_ALL_TREE_BY_USER_ID_SUCCESS = 'GET_ALL_TREE_BY_USER_ID_SUCCESS';
export const GET_ALL_TREE_BY_USER_ID_FAILURE = 'GET_ALL_TREE_BY_USER_ID_FAILURE';


export const CLEAR_ANY_DEAD_TREES = 'CLEAR_ANY_DEAD_TREES';

export const GET_COMBINE_TREE_BY_USER_ID_SUCCESS = 'GET_COMBINE_TREE_BY_USER_ID_SUCCESS';
export const GET_COMBINE_TREE_BY_USER_ID_FAILURE = 'GET_COMBINE_TREE_BY_USER_ID_FAILURE';

export const CHECK_ANY_DEAD_TREES_SUCCESS = 'CHECK_ANY_DEAD_TREES_SUCCESS';
export const CHECK_ANY_DEAD_TREES_FAILURE = 'CHECK_ANY_DEAD_TREES_FAILURE';


export const CHECK_PARAM_BEFOR_SUCCESS = 'CHECK_PARAM_BEFOR_SUCCESS';
export const CHECK_PARAM_BEFOR_FAILURE = 'CHECK_PARAM_BEFOR_FAILURE';