export const GET_OBJS_SUCCESS = 'GET_OBJS_SUCCESS';
export const GET_OBJS_FAILURE = 'GET_OBJS_FAILURE';

export const GET_MY_OBJS_SUCCESS = 'GET_MY_OBJS_SUCCESS';
export const GET_MY_OBJS_FAILURE = 'GET_MY_OBJS_FAILURE';

export const GET_DETAIL_OBJ_SUCCESS = 'GET_DETAIL_OBJ_SUCCESS';
export const GET_DETAIL_OBJ_FAILURE = 'GET_DETAIL_OBJ_FAILURE';

export const MOVE_TREE_TO_MAP_SUCCESS = 'MOVE_TREE_TO_MAP_SUCCESS';
export const MOVE_TREE_TO_MAP_FAILURE = 'MOVE_TREE_TO_MAP_FAILURE';
export const CLEAR_MOVE_TREE_TO_MAP = 'CLEAR_MOVE_TREE_TO_MAP';

export const GET_ONLAND_OBJS_BY_USERID_SUCCESS = 'GET_ONLAND_OBJS_BY_USERID_SUCCESS';
export const GET_ONLAND_OBJS_BY_USERID_FAILURE = 'GET_ONLAND_OBJS_BY_USERID_FAILURE';

export const REMOVE_OBJS = 'REMOVE_OBJS';

export const UPDATE_OBJS = 'UPDATE_OBJS';

export const SET_TREE_DIES = 'SET_TREE_DIES';

export const GET_OBJS_AREA_SUCCESS = 'GET_OBJS_AREA_SUCCESS';
export const GET_OBJS_AREA_FAILURE = 'GET_OBJS_AREA_FAILURE';

export const GET_OBJECT_BY_QUADKEY_SUCCESS = 'GET_OBJECT_BY_QUADKEY_SUCCESS';
export const GET_OBJECT_BY_QUADKEY_FAILURE = 'GET_OBJECT_BY_QUADKEY_FAILURE';

export const GET_LAND_SELECTED_MY_LAND = 'GET_LAND_SELECTED_MY_LAND';
export const GET_CATEGORY_SELECTED_MY_LAND = 'GET_CATEGORY_SELECTED_MY_LAND';

export const GET_LAND_TREES_SUCCESS = "GET_LAND_TREES_SUCCESS";
export const GET_LAND_TREES_FAILURE = "GET_LAND_TREES_FAILURE";

export const GET_LAND_PLANT_TREE = 'GET_LAND_PLANT_TREE';
export const GET_LAND_REMOVE_TREE = 'GET_LAND_REMOVE_TREE';

export const GET_CURRENT_CATEGORY_ID = 'GET_CURRENT_CATEGORY_ID';