export const GET_SHOPS_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOPS_RANDOM_BOX_SUCCESS = 'GET_SHOPS_RANDOM_BOX_SUCCESS';
export const GET_SHOPS_RANDOM_BOX_FAILURE = 'GET_SHOPS_RANDOM_BOX_FAILURE';

export const GET_SHOPS_FAILURE = 'GET_SHOP_FAILURE';
export const BUY_SHOPS_SUCCESS = 'BUY_SHOPS_SUCCESS';

export const CLEAR_RESULT_STATUS = 'CLEAR_RESULT_STATUS';

