export const REQUEST_BITAMIN_HISTORY = 'REQUEST_BITAMIN_HISTORY';
export const GET_MY_BITAMIN_SUCCESS = 'GET_MY_BITAMIN_SUCCESS';
export const GET_MY_BITAMIN_FAILURE = 'GET_MY_BITAMIN_FAILURE';
export const GET_BITAMIN_HISTORY_RECEIVE_SUCCESS = 'GET_BITAMIN_HISTORY__RECEIVE_SUCCESS';
export const GET_BITAMIN_HISTORY_USE_SUCCESS = 'GET_BITAMIN_HISTORY_USE_SUCCESS';
export const GET_BITAMIN_HISTORY_CONVERT_SUCCESS = 'GET_BITAMIN_HISTORY_CONVERT_SUCCESS';
export const GET_BITAMIN_HISTORY_FAILURE = 'GET_BITAMIN_HISTORY_FAILURE';
export const EXCHANGE_BITAMIN_SUCCESS = 'EXCHANGE_BITAMIN_SUCCESS';
export const EXCHANGE_BITAMIN_FAILURE = 'EXCHANGE_BITAMIN_FAILURE';
export const RESET_STATUS = 'RESET_STATUS';

