export const GET_SELL_LAND_INFOS_SUCCESS = 'GET_SELL_LAND_INFOS_SUCCESS';
export const GET_SELL_LAND_INFOS_FAILURE = 'GET_SELL_LAND_INFOS_FAILURE';
export const REMOVE_SELL_LAND_INFOS = 'REMOVE_SELL_LAND_INFOS';

export const CLEAR_PURCHASE_STATUS_SOCKET = 'CLEAR_PURCHASE_STATUS_SOCKET';

export const LANDS_GETALLCATEGORY_SUCCESS = 'LANDS_GETALLCATEGORY_SUCCESS';
export const LANDS_GETALLCATEGORY_FAILURE = 'LANDS_GETALLCATEGORY_FAILURE';

export const GET_ALL_LAND = 'GET_ALL_LAND';
export const GET_ALL_LAND_SUCCESS = 'GET_ALL_LAND_SUCCESS';
export const GET_ALL_LAND_FAILURE = 'GET_ALL_LAND_FAILURE';
//export const GET_ALL_LAND_BY_ID = 'GET_ALL_LAND_BY_ID';

export const GET_ALL_LAND_MARK_CATEGORY = 'GET_ALL_LAND_MARK_CATEGORY';
export const GET_ALL_LAND_MARK_CATEGORY_SUCCESS = 'GET_ALL_LAND_MARK_CATEGORY_SUCCESS';
export const GET_ALL_LAND_MARK_CATEGORY_FAILURE = 'GET_ALL_LAND_MARK_CATEGORY_FAILURE';

export const GET_LAND_BY_CATEGORY = 'GET_LAND_BY_CATEGORY';
export const GET_LAND_BY_CATEGORY_SUCCESS = 'GET_LAND_BY_CATEGORY_SUCCESS';
export const GET_LAND_BY_CATEGORY_FAILURE = 'GET_LAND_BY_CATEGORY_FAILURE';

export const GET_ALL_LAND_BY_ID_SUCCESS = 'GET_ALL_LAND_BY_ID_SUCCESS';
export const GET_ALL_LAND_BY_ID_FAILURE = 'GET_ALL_LAND_BY_ID_FAILURE';
export const GET_DEFAULT = 'GET_DEFAULT';
export const GET_DEFAULT_SUCCESS = 'GET_DEFAULT_SUCCESS';
export const GET_DEFAULT_FAILURE = 'GET_DEFAULT_FAILURE';

export const GET_MY_LAND_FROM_STORE = 'GET_MY_LAND_FROM_STORE';

export const GET_ALL_HISTORY_TRADING_LAND_BY_ID_SUCCESS = 'GET_ALL_HISTORY_TRADING_LAND_BY_ID_SUCCESS';
export const GET_ALL_HISTORY_TRADING_LAND_BY_ID_FAILURE = 'GET_ALL_HISTORY_TRADING_LAND_BY_ID_FAILURE';

export const SAVE_LAND_SELECTED_POSITION = 'SAVE_LAND_SELECTED_POSITION';

export const ADD_CENTER_CATEGORY_SUCCESS = 'ADD_CENTER_CATEGORY_SUCCESS';
export const ADD_CENTER_CATEGORY_FAILURE = 'ADD_CENTER_CATEGORY_FAILURE';

export const GET_ALL_LAND_MARK_CATEGORY_IN_MAP_SUCCESS = 'GET_ALL_LAND_MARK_CATEGORY_IN_MAP_SUCCESS';
export const GET_ALL_LAND_MARK_CATEGORY_IN_MAP_FAILURE = 'GET_ALL_LAND_MARK_CATEGORY_IN_MAP_FAILURE';

export const GET_ALL_LAND_CATEGORY_SUCCESS = 'GET_ALL_LAND_CATEGORY_SUCCESS';
export const GET_ALL_LAND_CATEGORY_FAILURE = 'GET_ALL_LAND_CATEGORY_FAILURE';

export const TRANSFER_LAND_CATEGORY_SUCCESS = 'TRANSFER_LAND_CATEGORY_SUCCESS';
export const TRANSFER_LAND_CATEGORY_FAILURE = 'TRANSFER_LAND_CATEGORY_FAILURE';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

export const EDIT_LAND_SUCCESS = 'EDIT_LAND_SUCCESS';
export const EDIT_LAND_FAILURE = 'EDIT_LAND_FAILURE';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const DELETE_LAND_CATEGORY_SUCCESS = 'DELETE_LAND_CATEGORY_SUCCESS';
export const DELETE_LAND_CATEGORY_FAILURE = 'DELETE_LAND_CATEGORY_FAILURE';

export const GET_LAND_BY_CATEGORY_FOR_CHECKING_SUCCESS = 'GET_LAND_BY_CATEGORY_FOR_CHECKING_SUCCESS';
export const GET_LAND_BY_CATEGORY_FOR_CHECKING_FAILURE = 'GET_LAND_BY_CATEGORY_FOR_CHECKING_FAILURE';

export const CHANGE_LAND_MARK_STATE_REQUEST = 'CHANGE_LAND_MARK_STATE_REQUEST';
export const CHANGE_LAND_MARK_STATE_SUCCESS = 'CHANGE_LAND_MARK_STATE_SUCCESS';
export const CHANGE_LAND_MARK_STATE_FAILURE = 'CHANGE_LAND_MARK_STATE_FAILURE';

export const GET_LATEST_QUADKEY_LAND_PURCHASE = 'GET_LATEST_QUADKEY_LAND_PURCHASE';

export const GET_AREA_LAND_SUCCESS = 'GET_AREA_LAND_SUCCESS';
export const GET_AREA_LAND_FAILURE = 'GET_AREA_LAND_FAILURE';

export const GET_LAND_INFO_SUCCESS = 'GET_LAND_INFO_SUCCESS';
export const GET_LAND_INFO_FAILURE = 'GET_LAND_INFO_FAILURE';

export const GET_LAND_BY_QUADKEY_SUCCESS = 'GET_LAND_BY_QUADKEY_SUCCESS';
export const GET_LAND_BY_QUADKEY_FAILURE = 'GET_LAND_BY_QUADKEY_FAILURE';


export const GET_ALL_LAND_CATEGORY_NEW_SUCCESS = 'GET_ALL_LAND_CATEGORY_NEW_SUCCESS';
export const GET_ALL_LAND_CATEGORY_NEW_FAILURE = 'GET_ALL_LAND_CATEGORY_NEW_FAILURE';

export const GET_LAND_BY_QUADKEY_NEW_SUCCESS = 'GET_LAND_BY_QUADKEY_NEW_SUCCESS';
export const GET_LAND_BY_QUADKEY_NEW_FAILURE = 'GET_LAND_BY_QUADKEY_NEW_FAILURE';

export const TRANSFER_LAND_CATEGORY_NEW_SUCCESS = 'TRANSFER_LAND_CATEGORY_NEW_SUCCESS';

export const REMOVE_BUY_LAND_STATUS = 'REMOVE_BUY_LAND_STATUS';
